### ISSUE TITLE
This part feels like an incomplete thought

### ISSUE THREAD

**Issue by morgvanny** [learn-co-curriculum/react-introduction-to-react-router#11]
> It is good to know though, that modern search engine spiders are able to read

Unlike similarly formatted parts of this readme, this doesn't end with a period. We could, of course, just add one, but even then it feels like an incomplete thought. I know what it's getting at, but it feels awkward to me.

**Comment by maxwellbenton** [comment]
Hey @morgvanny,

Agreed. I've removed it - while there is some interesting stuff to be said about the fact that search engine spiders are able to render react router pages because they effectively run their own virtual browsers, it doesn't really fit where it was and it's hard to say with confidence that all of that is 100% accurate.
